config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users

  delete '/users/downgrade', to: 'users#downgrade', as: :downgrade
  #delete '/wikis/:wiki_id/collaborators/:user_id', to: 'collaborator#delete', as: :delete

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount < ApplicationRecord
  def self.default
    15_00
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  attr_accessor :email

  belongs_to :user
  belongs_to :wiki

  validates_uniqueness_of :user,
                          :scope => :wiki_id,
                          :message => "%{user.username} is already a Collaborator"

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators

  after_initialize :init

  enum role: [:standard, :premium, :admin]

  def init
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  before_save { self.private ||= false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  private
  def require_sign_in
    unless current_user
      flash[:alert] = "You must be logged in to do that"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def show
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is Not the user_id in your app
      amount: Amount.default,
      description: "Premium Membership - #{current_user.username}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for your payment, #{current_user.username}!"
    current_user.update_attribute(:role, 'premium')
    redirect_to wikis_path # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.username}",
      amount: Amount.default
    }
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :authorize_premium

  def create
    @wiki = Wiki.find(params[:wiki_id])
    user = User.find_by(email: params[:collaborator][:email])
    @collaborator = Collaborator.new(wiki: @wiki, user: user)

    if @collaborator.save
      flash[:notice] = "Collaborator added."
    else
      flash[:alert] = "Action failed. Collaborator was not added."
    end
      redirect_to edit_wiki_path(@wiki)
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = @wiki.collaborators.find(params[:id])

    if collaborator.destroy
      flash[:notice] = "Collaborator removed."
    else
      flash[:alert] = "Removal of collaborator failed."
    end
      redirect_to edit_wiki_path(@wiki)
  end

  private

  def authorize_premium
    unless current_user.premium? || current_user.admin?
      flash[:alert] = "You must be a premium user or admin to do that."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    current_user.standard!
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
    redirect_to edit_user_registration_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :require_sign_in, except: [:show, :index]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(post_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the wiki, please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(post_params)
    authorize @wiki
    if @wiki.update(post_params)
      redirect_to @wiki
    else
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def post_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_role_standard?
    current_user.role == 'standard'
  end

  def markdown(text)
    options = {
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      strikethrough: true,
      superscript: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def can_make_wiki_private?
    current_user.admin? || current_user.premium?
  end

  def can_view_wiki?(w)
    current_user == w.user || !w.private?
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click Here to Upgrade Plan to Premium!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/charges/show.html.erb
<h1>Charges#show</h1>
<p>Find me in app/views/charges/show.html.erb</p>

app/views/collaborators/_collaborator.html.erb
<div class="media">
  <div class="media-body">
    <% collab_user = User.find_by(id: collaborator.user_id) %>
    <strong><%= collab_user.username %></strong> <%= link_to "Delete Collaborator", wiki_collaborator_path(@wiki, collaborator), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this collaborator?' } %>
  </div>
</div>

app/views/collaborators/_form.html.erb
<h4>Add a collaborator</h4>
<%= form_for [wiki, collaborator] do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', placeholder: "Enter user email" %>
    <br>
    <%= f.submit "Add Collaborator", class: 'btn btn-success' %>
  </div>
<% end %>
<h4>Current Collaborators:</h4>
<div>
  <%= render wiki.collaborators %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul class="nav nav-tabs">
          <li class="nav-item pull-left"><%= link_to "Home", welcome_index_path %></li>
          <li class="nav-item pull-left"><%= link_to "Wikis", wikis_path %></li>
            <% if user_signed_in? %>
              <li class="nav-item pull-right"><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="nav-item pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
              <li class="nav-item pull-right">
                <a class="nav-link disabled" href="#">Signed in as: <strong><%= current_user.username %></strong> - </a>
              </li>

            <% else %>
              <li class="nav-item pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
              <li class="nav-item pull-right"><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
        </ul>
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter title here." %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body content here."%>
  </div>
  <% if can_make_wiki_private? %>
    <div class="form-group checkbox">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki?
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit "<%= @wiki.title %>"</h1>

<div class="row">
  <div class="col-md-4">
    <p>Edit Wiki Here</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <%= render 'collaborators/form', collaborator: Collaborator.new, wiki: @wiki %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<div>
  <p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>
</div>

<% @wikis.each do |wiki| %>

  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>

<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Create New Wiki Here</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<h4><%= markdown(@wiki.body) %></h4>
<small>Created by: <%= @wiki.user.username %> at: <%= @wiki.created_at %></small>
<div>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
</div>